In [19]:
from keras.models import Sequential
from keras.layers.core import Dense,Dropout,Activation,Flatten
from keras.layers.convolutional import Convolution2D,MaxPooling2D
from keras.utils import np_utils
from keras.preprocessing.image import  img_to_array

In [20]:
import numpy as np
import pandas as pd
import keras

In [21]:
data=pd.read_csv('train.csv')

In [22]:
data

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
5          0       0       0       0       0       0       0       0       0   
6          7       0       0       0       0       0       0       0       0   
7          3       0       0       0       0       0       0       0       0   
8          5       0       0       0       0       0       0       0       0   
9          3       0       0       0       0       0       0       0       0   
10         8       0       0       0       0       0       0       0       0   
11         9       0       0       0       0       0       0       0       0   
12         1       0       0       0       0       0       0       0       0   
13         3       0       0       0       0       0       0       0       0   
14         3       0       0       0       0       0       0       0       0   
15         1       0       0       0       0       0       0       0       0   
16         2       0       0       0       0       0       0       0       0   
17         0       0       0       0       0       0       0       0       0   
18         7       0       0       0       0       0       0       0       0   
19         5       0       0       0       0       0       0       0       0   
20         8       0       0       0       0       0       0       0       0   
21         6       0       0       0       0       0       0       0       0   
22         2       0       0       0       0       0       0       0       0   
23         0       0       0       0       0       0       0       0       0   
24         2       0       0       0       0       0       0       0       0   
25         3       0       0       0       0       0       0       0       0   
26         6       0       0       0       0       0       0       0       0   
27         9       0       0       0       0       0       0       0       0   
28         9       0       0       0       0       0       0       0       0   
29         7       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41970      2       0       0       0       0       0       0       0       0   
41971      3       0       0       0       0       0       0       0       0   
41972      4       0       0       0       0       0       0       0       0   
41973      4       0       0       0       0       0       0       0       0   
41974      3       0       0       0       0       0       0       0       0   
41975      9       0       0       0       0       0       0       0       0   
41976      2       0       0       0       0       0       0       0       0   
41977      4       0       0       0       0       0       0       0       0   
41978      4       0       0       0       0       0       0       0       0   
41979      4       0       0       0       0       0       0       0       0   
41980      7       0       0       0       0       0       0       0       0   
41981      2       0       0       0       0       0       0       0       0   
41982      8       0       0       0       0       0       0       0       0   
41983      7       0       0       0       0       0       0       0       0   
41984      3       0       0       0       0       0       0       0       0   
41985      3       0       0       0       0       0       0       0       0   
41986      0       0       0       0       0       0       0       0       0   
41987      5       0       0       0       0       0       0       0       0   
41988  

In [23]:
data.iloc[3,1:].values.reshape(28,28).astype('uint8')


array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0, 220, 179,   6,   0,   0,   0,   0,
          0,   0,   0,   0,   9,  77,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [24]:
df_x = data.iloc[:,1:].values.reshape(len(data),28,28,1)

#Storing the labels in y
y = data.iloc[:,0].values

In [25]:
df_y = keras.utils.to_categorical(y,num_classes=10)


In [26]:
df_x = np.array(df_x)/255
df_y = np.array(df_y)

In [27]:
y

array([1, 0, 1, ..., 7, 6, 9], dtype=int64)

In [28]:
df_y

array([[ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [29]:
df_x.shape


(42000, 28, 28, 1)

In [48]:
model = Sequential()
model.add(Convolution2D(32,3,data_format='channels_last',activation='relu',input_shape=(28,28,1)))
model.add(Convolution2D(64,5,data_format='channels_last',activation='relu'))



model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(100))
model.add(Dropout(0.2))
model.add(Dense(10))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer = 'adadelta', metrics = ['accuracy'])

In [49]:

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_9 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
conv2d_10 (Conv2D)           (None, 22, 22, 64)        51264     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 11, 11, 64)        0         
_________________________________________________________________
flatten_3 (Flatten)          (None, 7744)              0         
_________________________________________________________________
dense_5 (Dense)              (None, 100)               774500    
_________________________________________________________________
dropout_3 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_6 (Dense)              (None, 10)                1010      
__________

In [50]:
model.fit(df_x,df_y)

Epoch 1/10
42000/42000 [==============================] - 298s 7ms/step - loss: 0.1603 - acc: 0.9522
Epoch 2/10
42000/42000 [==============================] - 283s 7ms/step - loss: 0.0582 - acc: 0.9826
Epoch 3/10
42000/42000 [==============================] - 305s 7ms/step - loss: 0.0435 - acc: 0.9868
Epoch 4/10
42000/42000 [==============================] - 303s 7ms/step - loss: 0.0353 - acc: 0.9891
Epoch 5/10
42000/42000 [==============================] - 302s 7ms/step - loss: 0.0280 - acc: 0.9911
Epoch 6/10
42000/42000 [==============================] - 303s 7ms/step - loss: 0.0252 - acc: 0.9921
Epoch 7/10
42000/42000 [==============================] - 283s 7ms/step - loss: 0.0211 - acc: 0.9934
Epoch 8/10
42000/42000 [==============================] - 288s 7ms/step - loss: 0.0180 - acc: 0.9946
Epoch 9/10
42000/42000 [==============================] - 283s 7ms/step - loss: 0.0149 - acc: 0.9957
Epoch 10/10
42000/42000 [==============================] - 335s 8ms/step - loss: 0.0140 - a

In [51]:
test=pd.read_csv('test.csv')

In [52]:
test.shape

(28000, 784)

In [53]:
test['id']=range(1,len(test)+1)
test.tail()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
27995       0       0       0       0       0       0       0       0       0   
27996       0       0       0       0       0       0       0       0       0   
27997       0       0       0       0       0       0       0       0       0   
27998       0       0       0       0       0       0       0       0       0   
27999       0       0       0       0       0       0       0       0       0   

       pixel9  ...    pixel775  pixel776  pixel777  pixel778  pixel779  \
27995       0  ...           0         0         0         0         0   
27996       0  ...           0         0         0         0         0   
27997       0  ...           0         0         0         0         0   
27998       0  ...           0         0         0         0         0   
27999       0  ...           0         0         0         0         0   

       pixel780  pixel781  pixel782  pixel783     id  
27995         0         0         0         0  27996  
27996         0         0         0         0  27997  
27997         0         0         0         0  27998  
27998         0         0         0         0  27999  
27999         0         0         0         0  28000  

[5 rows x 785 columns]

In [54]:
w=test.pop('id')
w.shape

(28000,)

In [55]:
test.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 784 columns]

In [56]:
#test.iloc[3,:].values.reshape(28,28).astype('uint8')


In [57]:
test_x = test.iloc[:,:].values.reshape(len(test),28,28,1)

test_x.shape

(28000, 28, 28, 1)

In [58]:
test_x=test_x/255

In [59]:
y_pred=model.predict(test_x)
y_pred.shape

(28000, 10)

In [60]:
a=[11,12,13,14]
z=np.argmax(a)
z

3

In [61]:
max=np.argmax(y_pred,axis=1)               

In [62]:
max

array([2, 0, 9, ..., 3, 9, 2], dtype=int64)

In [63]:
max.shape

(28000,)

In [64]:
submission=pd.DataFrame({"ImageId":w,"Label":max})
submission.to_csv('mnist2.csv',index=False)
len(submission)


28000

In [65]:
submission

ImageId  Label
0            1      2
1            2      0
2            3      9
3            4      9
4            5      3
5            6      7
6            7      0
7            8      3
8            9      0
9           10      3
10          11      5
11          12      7
12          13      4
13          14      0
14          15      4
15          16      3
16          17      3
17          18      1
18          19      9
19          20      0
20          21      9
21          22      1
22          23      1
23          24      5
24          25      7
25          26      4
26          27      2
27          28      7
28          29      4
29          30      7
...        ...    ...
27970    27971      5
27971    27972      0
27972    27973      4
27973    27974      8
27974    27975      0
27975    27976      3
27976    27977      6
27977    27978      0
27978    27979      1
27979    27980      9
27980    27981      3
27981    27982      1
27982    27983      1
27983    27984      0
27984    27985      4
27985    27986      5
27986    27987      2
27987    27988      2
27988    27989      9
27989    27990      6
27990    27991      7
27991    27992      6
27992    27993      1
27993    27994      9
27994    27995      7
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2

[28000 rows x 2 columns]