In [1]:
import tensorflow as tf
import numpy as np

In [2]:
from tensorflow.examples.tutorials.mnist import input_data

In [3]:
data=input_data.read_data_sets("data/MNIST/",one_hot=True)

Extracting data/MNIST/train-images-idx3-ubyte.gz
Extracting data/MNIST/train-labels-idx1-ubyte.gz
Extracting data/MNIST/t10k-images-idx3-ubyte.gz
Extracting data/MNIST/t10k-labels-idx1-ubyte.gz


AttributeError: 'DataSet' object has no attribute 'shape'

In [10]:
len(data.train.labels)

55000

In [11]:
len(data.test.labels)

10000

In [13]:
len(data.validation.labels)

5000

In [14]:
data.test.labels[0:5,:]  #labels

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]])

In [15]:
data.train.labels[0:5,:]  #labels in form of array

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [16]:
data.test.cls=np.array([label.argmax() for label in data.test.labels])

In [17]:
data.test.cls[0:5] #labels

array([7, 2, 1, 0, 4], dtype=int64)

In [18]:
img_size=28
img_size_flat=28*28
img_shape=(img_size,img_size)
num_classes=10 #0-9

In [19]:
#computational graph
x=tf.placeholder(tf.float32,[None,img_size_flat])
y_true=tf.placeholder(tf.float32,[None,num_classes])

In [20]:
y_true_cls=tf.placeholder(tf.int64,[None])

In [21]:
weights=tf.Variable(tf.zeros([img_size_flat,num_classes]))

In [24]:
biases=tf.Variable(tf.zeros([num_classes]))

In [25]:
logits=tf.matmul(x,weights)+biases #length 10

In [27]:
y_pred=tf.nn.softmax(logits) #length 10

In [29]:
y_pred_cls=tf.argmax(y_pred,axis=1)

In [31]:
    cross_entropy=tf.nn.softmax_cross_entropy_with_logits(logits=logits,labels=y_true)

In [32]:
cost=tf.reduce_mean(cross_entropy)

In [1]:
optimizer=tf.train.GradientDescentOptimizer(learning_rate=.5).minimize(cost)

NameError: name 'tf' is not defined

In [35]:
correct_prediction=tf.equal(y_pred_cls,y_true_cls)

In [36]:
accuracy=tf.reduce_mean(tf.cast(correct_prediction,tf.float32)) #total +ve/total

In [37]:
session=tf.Session()

In [39]:
session.run(tf.global_variables_initializer())

In [40]:
    batch_size=100

In [41]:
def optimize(num_iterations):
    for i in range(num_iterations):
        x_batch,y_true_batch=data.train.next_batch(batch_size) #100 images & 100 labels
        feed_dict_train={x:x_batch,y_true:y_true_batch}
        session.run(optimizer,feed_dict=feed_dict_train)

In [42]:
feed_dict_test={x:data.test.images,y_true:data.test.labels,y_true_cls:data.test.cls}

In [43]:
def print_accuracy():
    acc=session.run(accuracy,feed_dict=feed_dict_test)
    print(acc)

In [53]:
optimize(num_iterations=10000)

In [54]:
print_accuracy()

0.9246
